"""Builds course.json (calendar) and lexique.json (glossary)."""
import json, os
D = os.path.join(os.path.dirname(__file__), '..', 'public', 'content')
ALL = [1, 2, 3, 5, 8, 9, 11, 12, 13]

course = {
    "course": "420-1C6-JR Programmation structurée",
    "session": "Automne 2026",
    "week1Start": "2026-08-24",
    "breakAfterWeek": 7,
    "weeks": [
        {"week": 1, "type": "teach", "title": "Premiers pas"},
        {"week": 2, "type": "teach", "title": "Entrées, sorties et conditions"},
        {"week": 3, "type": "teach", "title": "Switch, constantes et portée"},
        {"week": 4, "type": "review", "title": "Révision · Examen 1", "reviewWeeks": [1, 2, 3]},
        {"week": 5, "type": "teach", "title": "Les boucles"},
        {"week": 6, "type": "review", "title": "Exercices sur les boucles", "reviewWeeks": [5]},
        {"week": 7, "type": "review", "title": "Révision · Examen 2", "reviewWeeks": [1, 2, 3, 5]},
        {"week": 8, "type": "teach", "title": "Les fonctions"},
        {"week": 9, "type": "teach", "title": "Modulo et hasard"},
        {"week": 10, "type": "review", "title": "Révision · Examen 3", "reviewWeeks": [8, 9]},
        {"week": 11, "type": "teach", "title": "Tableaux et vector"},
        {"week": 12, "type": "teach", "title": "Structures et chaînes"},
        {"week": 13, "type": "teach", "title": "Les fichiers texte"},
        {"week": 14, "type": "review", "title": "Synthèse · Volets A et B", "reviewWeeks": ALL},
        {"week": 15, "type": "review", "title": "Synthèse · Volets A et B", "reviewWeeks": ALL},
    ],
    "exams": [
        {"id": "ex1", "label": "Examen 1", "week": 4, "weight": "10 %", "mockWeeks": [1, 2, 3]},
        {"id": "ex2", "label": "Examen 2", "week": 7, "weight": "25 %", "mockWeeks": [1, 2, 3, 5]},
        {"id": "ex3", "label": "Examen 3", "week": 10, "weight": "15 %", "mockWeeks": [1, 2, 3, 5, 8, 9]},
        {"id": "voletb", "label": "Volet B (entretiens)", "week": 13, "weight": "20 %", "mockWeeks": None},
        {"id": "voleta", "label": "Volet A (TP remis)", "week": 15, "weight": "10 %", "mockWeeks": None},
        {"id": "voletc", "label": "Volet C (final)", "week": 16, "weight": "20 %", "mockWeeks": ALL},
    ],
}
json.dump(course, open(os.path.join(D, 'course.json'), 'w'), ensure_ascii=False, indent=1)

lexique = [
    ["Algorithme", "Suite d'étapes précises pour résoudre un problème. Comme une recette de croquettes.", 1],
    ["Assignation", "Mettre une valeur dans une variable avec `=`. Ex : `age = 20;`", 1],
    ["Commentaire", "Texte ignoré par le compilateur : `// une ligne` ou `/* plusieurs lignes */`.", 1],
    ["Compilation", "Traduction du code source C++ en programme exécutable (.exe).", 1],
    ["Erreur de compilation", "Le compilateur refuse ton code (ex : `;` manquant). Le programme ne démarre pas.", 1],
    ["Déclaration", "Créer une variable en donnant son type et son nom : `int age;`", 1],
    ["Littéral", "Valeur écrite directement dans le code : `10`, `1.5`, `'a'`, `\"bonjour\"`.", 1],
    ["Octet", "8 bits. Un `int` prend souvent 4 octets, un `double` 8, un `char` 1.", 1],
    ["Syntaxe", "Les règles d'écriture du langage (où vont les `;`, les accolades...).", 1],
    ["Sémantique", "Le sens du code : ce qu'il fait vraiment. Du code peut compiler et être faux !", 1],
    ["camelCase", "Style de nom : premier mot en minuscule, les suivants avec majuscule. Ex : `nbEtudiants`.", 1],
    ["Concaténation", "Coller des morceaux de texte ensemble, ex : `\"Salut \" + nom`.", 2],
    ["Namespace (espace de noms)", "Un « nom de famille » pour ranger des outils. `std::cout` = cout de la famille std.", 2],
    ["Troncation", "Couper la partie décimale : `7 / 2` donne `3` avec deux int.", 2],
    ["Conversion (cast)", "Changer le type d'une valeur : `(double)7 / 2` donne `3.5`.", 2],
    ["Booléen (bool)", "Type qui vaut seulement `true` ou `false`.", 2],
    ["Condition", "Expression vraie ou fausse testée par un `if`, un `while`...", 2],
    ["Constante", "Variable qui ne peut plus changer : `const int NB_MAX = 10;`", 3],
    ["UPPER_SNAKE_CASE", "Style de nom pour les constantes : tout en majuscules, mots séparés par `_`.", 3],
    ["Portée (scope)", "Zone du code où une variable existe : entre ses accolades `{ }`.", 3],
    ["Variable globale", "Déclarée hors de toute fonction : visible partout. À éviter (sauf constantes).", 3],
    ["enum (énumération)", "Type avec une liste de valeurs nommées : `enum Couleur { ROUGE, VERT };`", 3],
    ["Epsilon", "Toute petite marge pour comparer deux double : `abs(a - b) < 0.0001`.", 3],
    ["Opérateur ternaire", "If/else en une ligne : `condition ? siVrai : siFaux`.", 3],
    ["Jeu de test (plan de test)", "Liste d'entrées + résultats attendus pour vérifier qu'un programme marche.", 3],
    ["Boucle (itération)", "Répéter un bloc de code tant qu'une condition est vraie.", 5],
    ["Itération", "Un tour de boucle.", 5],
    ["Incrémentation", "Ajouter 1 : `++i` (pré) ou `i++` (post).", 5],
    ["Décrémentation", "Enlever 1 : `--i` ou `i--`.", 5],
    ["Boucle imbriquée", "Une boucle à l'intérieur d'une autre boucle.", 5],
    ["Boucle infinie", "Boucle dont la condition ne devient jamais fausse. Le programme gèle !", 5],
    ["Off-by-one", "Erreur d'un tour de trop ou de moins (ex : `<=` au lieu de `<`).", 5],
    ["Fonction", "Bloc de code nommé et réutilisable, appelé avec des parenthèses : `calculerMoyenne()`.", 8],
    ["Paramètre", "Variable qui reçoit une valeur quand on appelle la fonction.", 8],
    ["Argument", "Valeur donnée à la fonction au moment de l'appel.", 8],
    ["Prototype", "Déclaration d'une fonction sans son corps : `int doubler(int x);`", 8],
    ["Valeur de retour", "Ce que la fonction renvoie avec `return`.", 8],
    ["Passage par valeur", "La fonction reçoit une COPIE : l'original ne change pas.", 8],
    ["Passage par référence (&)", "La fonction reçoit l'ORIGINAL : elle peut le modifier.", 8],
    ["Pile d'appels", "Liste des fonctions en cours d'exécution, la plus récente en haut.", 8],
    ["Édition de liens", "Étape après la compilation qui relie les appels aux corps des fonctions.", 8],
    ["Erreur de liens", "Le corps d'une fonction est introuvable (ex : LNK2019 dans Visual Studio).", 8],
    ["Point d'arrêt", "Marque rouge dans Visual Studio où le programme se met en pause pour déboguer.", 8],
    ["Modulo (%)", "Le reste d'une division entière : `7 % 3` donne `1`.", 9],
    ["Pseudo-aléatoire", "Nombres qui ont l'air au hasard mais viennent d'un calcul (graine + formule).", 9],
    ["Graine (seed)", "Valeur de départ du hasard, donnée par `srand(time(0))`.", 9],
    ["Refactorisation", "Réorganiser du code (ex : en fonctions) sans changer ce qu'il fait.", 9],
    ["Tableau", "Suite de cases du même type, collées en mémoire : `int notes[5];`", 11],
    ["Indice (index)", "Numéro d'une case, qui commence à 0.", 11],
    ["Tableau 2D", "Tableau de tableaux, comme une grille : `int grille[3][4];`", 11],
    ["vector", "Tableau qui peut grandir : `vector<int> v;` puis `v.push_back(3);`", 11],
    ["struct (structure)", "Type qui regroupe plusieurs variables : `struct Chat { string nom; int age; };`", 12],
    ["Membre (champ)", "Une variable à l'intérieur d'une struct : `monChat.nom`.", 12],
    ["Sous-chaîne", "Morceau d'une string, obtenu avec `substr(debut, longueur)`.", 12],
    ["string::npos", "Valeur spéciale renvoyée par `find()` quand rien n'est trouvé.", 12],
    ["Flux (stream)", "Canal par où passent les données : cout, cin, fichiers...", 13],
    ["ifstream / ofstream", "Flux pour lire (i = input) ou écrire (o = output) dans un fichier.", 13],
    ["Chemin relatif", "Chemin d'un fichier à partir du dossier courant du programme.", 13],
]
json.dump([{"term": t, "def": d, "week": w} for t, d, w in lexique],
          open(os.path.join(D, 'lexique.json'), 'w'), ensure_ascii=False, indent=1)
print(len(lexique), 'terms')
